### ISSUE TITLE
Are nested sentences deliberate or errors?

### ISSUE THREAD

**Issue by manning** [jsavelka/sbd_adjudicatory_dec#2]
There are things marked as sentences that are wholly contained in larger sentences. Are these errors or is this intended? Skimming the guidelines, I didn't see any mention of aiming to annotate nested sentences, and indeed the section on [Parentheticals within sentences](https://github.com/jsavelka/sbd_adjudicatory_dec/blob/master/LLT_sentence_annotation_protocol.md#parentheticals-within-sentences) suggests the opposite, even though there are some situations, such as that one or quotations of direct speech that could very reasonably be analyzed as involving embedded whole sentences.

The first two in `scotus.json` are:
37737-37854: Nor can § 16-6-2 be justified as a "morally neutral" exercise of Georgia's power to "protect the public environment,"
37737-37898: Nor can § 16-6-2 be justified as a "morally neutral" exercise of Georgia's power to "protect the public environment," Paris Adult Theatre I, 413 U. S., at 68-69.
37855-37898: Paris Adult Theatre I, 413 U. S., at 68-69.

54139-54354: At the time of the ratification of the Bill of Rights, Virginia had no specific statute outlawing sodomy, but had adopted the English common law. 9 Hening's Laws of Virginia, ch. 5, § 6, p. 127 (1821) (passed 1776).
54139-54284: At the time of the ratification of the Bill of Rights, Virginia had no specific statute outlawing sodomy, but had adopted the English common law.
54285-54354: 9 Hening's Laws of Virginia, ch. 5, § 6, p. 127 (1821) (passed 1776).

Both of these are citations, which makes it look like the more divided up form is correct based on [List B](https://github.com/jsavelka/sbd_adjudicatory_dec/blob/master/LLT_sentence_annotation_protocol.md#list-b-linguistic-transforms-of-normal-forms).

**Comment by jsavelka** [comment]
Chris,

Unfortunately, it really looks like you identified an error in our dataset. Your intuition is correct. In cases such as these the more divided form is correct. This error was introduced during the QA stage when on certain occasions the reviewers forgot to remove the long annotation after splitting it into multiple ones.

Fortunately, this error does not have any effect on the inter-annotator agreement that we measured as this was taken before the QA stage. It also does not have any effect on the performance of the various systems that we evaluated in the study as the evaluation was done on the level of boundaries. Hence, for example, the 37737-37854, 37737-37898, and 37855-37898 would map to 37737, 37854, 37855, 37898. The presence of the extra (erroneous) sentence with the 37737, 37898 offsets does not change anything there.

I have created a revision of the dataset where I have (hopefully) removed these redundant sentences. There were close to 150 of those across the whole dataset. As you are apparently working with the dataset, I have not pushed the revision into the master branch. Rather I have created a new [dataset_revision](https://github.com/jsavelka/sbd_adjudicatory_dec/tree/dataset_revision) branch - just in case it turns out I made a mistake somewhere along the line. Also, it is possible you will discover some more problems. Once, you are done with your work and we know there are no other known problems I will merge the branch to master.

Please, accept my apology for these problems. This is something we should have caught ourselves.

Finally, I would like to thank you for helping us improve the dataset and make sure it is as clean and nice as possible for others to use.

Please, let me know in case there are other problems and I would look into them ASAP.

Best regards.

Jaromir

**Comment by manning** [comment]
Hi Jaromir, although I started doing some investigations of this data in April, I'm afraid I haven't gotten back to it since, and who knows when/if I will. At present, I don't know of any other problems—phew!—so by all means feel free to merge this branch!

**Comment by jsavelka** [comment]
Thank you, Chris!
